resourceGroupName = "rm09"
location = "East US"
vnetname = "myterraformvnet"
subnetname = "myterraformsubnet"
ipaddressname = "myIpaddress"
nsgname = "mynsg"
nicname = "mynic"
virtualMachineName = "vm01"